### ISSUE TITLE
Package for Firefox

### ISSUE THREAD

**Issue by GGORG0** [MohammedMMC/HighSeas-Doubloons-Extension#4]
Hey, nice work! I'd like to use this extension, but I use Firefox. I've seen that it's pretty easy to port a Chrome extension to Firefox

**Comment by MohammedMMC** [comment]
Thank you! 
While I’m not very familiar with Firefox i know that adding Chrome extensions to Firefox can be a bit tricky.
In newer versions of Firefox extensions require a signature to be added.
If you have an old firefox version you may be able to add the extension but you should disable some options in the settings

However, you can still load the extension temporarily by following these steps (But i think it will be deleted when you restart firefox cuz its temporarily installed):

1. Download the repository files to your computer.  
2. Open Firefox and navigate to `about:debugging#/runtime/this-firefox` (or go to your Firefox settings and find the "Temporary Extensions" section).  
3. Click on **"Load Temporary Add-on."**  
4. Select the `manifest.json` file from the downloaded repository.  

I hope this helps! :) Sorry for not fully supporting Firefox 😞

**Comment by MohammedMMC** [comment]
i added the extension on firefox store, now you can add it easily
https://addons.mozilla.org/en-US/firefox/addon/highseas-doubloons/
