### ISSUE TITLE
Add Firefox support please :))

### ISSUE THREAD

**Issue by QinCai-rui** [MohammedMMC/HighSeas-Doubloons-Extension#5]
A lot of people (like me) use Firefox instead of Chromium. Can you please add a Firefox variant of the extension? Thanks!

**Comment by MohammedMMC** [comment]
i talked about it here: https://github.com/MohammedMMC/HighSeas-Doubloons-Extension/issues/4

But i will try to upload it to FireFox extensions store

**Comment by QinCai-rui** [comment]
ahhh ok thanks :)))

**Comment by MohammedMMC** [comment]
Added successfully 😃
**Chrome:** https://chromewebstore.google.com/detail/highseas-doubloons/hhimmaemgjmpjiipodpdmldffkemoajm
**Firefox:** https://addons.mozilla.org/en-US/firefox/addon/highseas-doubloons/
